import { api } from "@/utils/api";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Show() {
  const router = useRouter();
  const show = api.shows.getShowBySlug.useQuery({
    slug: router.query.slug as string,
  });

  return show.isLoading ? (
    <div>Loading...</div>
  ) : !show.data ? (
    <div>Error</div>
  ) : (
    <>
      <Head>
        <title>Show</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            {show.data?.name}
          </h1>
        </div>
      </main>
    </>
  );
}
